name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: submodules-init
      # You may pin to the exact commit or the version.
      # uses: snickerbockers/submodules-init@74927a8bb0fe1bb0f1f1e4d102384a8e69f19171
      uses: snickerbockers/submodules-init@v4
      
    - name: Github Action for wget
      # You may pin to the exact commit or the version.
      # uses: wei/wget@ca0a6b7f0fdd7ffbe9d4cec0b9696f2dc658d3c9
      uses: wei/wget@v1.1.1
      with:
        args: -O STM32CubeF4.zip https://github.com/STMicroelectronics/STM32CubeF4/archive/refs/tags/v1.26.2.zip
        
    - name: Decompress
      uses: TonyBogdanov/zip@1.0
      with:
          args: unzip -qq STM32CubeF4.zip -d SDK
          
    - name: check Cube Package
      run: ls ${{github.workspace}} -l && ls SDK -l

    - name: arm-none-eabi-gcc GNU Arm Embedded Toolchain
      uses: carlosperate/arm-none-eabi-gcc-action@v1.3.0
      with:
        # GNU Embedded Toolchain for Arm release name (e.g. "10.3-2021.07").
        release: 10.3-2021.07
        path-env-var: toolchain

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: STM32_CUBE_F4_PATH=SDK/STM32CubeF4-1.26.2 PATH=${PATH}:${{toolchain}}/bin cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      
